// automatically generated by the FlatBuffers compiler, do not modify
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
export { AddUserRequest } from './websocket-message/add-user-request.js';
export { AddUserResponse } from './websocket-message/add-user-response.js';
export { ChatListNotification } from './websocket-message/chat-list-notification.js';
export { ChatWithLatestMessage } from './websocket-message/chat-with-latest-message.js';
export { CreateChatRequest } from './websocket-message/create-chat-request.js';
export { CreateChatResponse } from './websocket-message/create-chat-response.js';
export { CreateMessageResponse } from './websocket-message/create-message-response.js';
export { ListChatsRequest } from './websocket-message/list-chats-request.js';
export { ListChatsResponse } from './websocket-message/list-chats-response.js';
export { ListMessagesRequest } from './websocket-message/list-messages-request.js';
export { ListMessagesResponse } from './websocket-message/list-messages-response.js';
export { ListUsersRequest } from './websocket-message/list-users-request.js';
export { ListUsersResponse } from './websocket-message/list-users-response.js';
export { Message } from './websocket-message/message.js';
export { MessageDB } from './websocket-message/message-db.js';
export { MessageNotification } from './websocket-message/message-notification.js';
export { Opcode } from './websocket-message/opcode.js';
export { Payload } from './websocket-message/payload.js';
export { SendMessageRequest } from './websocket-message/send-message-request.js';
export { UserListNotification } from './websocket-message/user-list-notification.js';

// export const WebsocketMessage = {
//     Message: message_js_1.Message,
//     Opcode: opcode_js_1.Opcode,
//     Payload: payload_js_1.Payload,
//     AddUserRequest: add_user_request_js_1.AddUserRequest,
//     AddUserResponse: add_user_response_js_1.AddUserResponse,
//     ChatListNotification: chat_list_notification_js_1.ChatListNotification,
//     ChatWithLatestMessage: chat_with_latest_message_js_1.ChatWithLatestMessage,
//     CreateChatRequest: create_chat_request_js_1.CreateChatRequest,
//     CreateChatResponse: create_chat_response_js_1.CreateChatResponse,
//     CreateMessageResponse: create_message_response_js_1.CreateMessageResponse,
//     ListChatsRequest: list_chats_request_js_1.ListChatsRequest,
//     ListChatsResponse: list_chats_response_js_1.ListChatsResponse,
//     ListMessagesRequest: list_messages_request_js_1.ListMessagesRequest,
//     ListMessagesResponse: list_messages_response_js_1.ListMessagesResponse,
//     ListUsersRequest: list_users_request_js_1.ListUsersRequest,
//     ListUsersResponse: list_users_response_js_1.ListUsersResponse,
//     MessageDB: message_db_js_1.MessageDB,
//     MessageNotification: message_notification_js_1.MessageNotification,
//     SendMessageRequest: send_message_request_js_1.SendMessageRequest,
//     UserListNotification: user_list_notification_js_1.UserListNotification
// };
