// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package WebsocketMessage

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type CreateChatRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsCreateChatRequest(buf []byte, offset flatbuffers.UOffsetT) *CreateChatRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &CreateChatRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishCreateChatRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsCreateChatRequest(buf []byte, offset flatbuffers.UOffsetT) *CreateChatRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &CreateChatRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedCreateChatRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *CreateChatRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *CreateChatRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *CreateChatRequest) Uid() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func CreateChatRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func CreateChatRequestAddUid(builder *flatbuffers.Builder, uid flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(uid), 0)
}
func CreateChatRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
