// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package WebsocketMessage

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type CreateChatResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsCreateChatResponse(buf []byte, offset flatbuffers.UOffsetT) *CreateChatResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &CreateChatResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishCreateChatResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsCreateChatResponse(buf []byte, offset flatbuffers.UOffsetT) *CreateChatResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &CreateChatResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedCreateChatResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *CreateChatResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *CreateChatResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *CreateChatResponse) ChatId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func CreateChatResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func CreateChatResponseAddChatId(builder *flatbuffers.Builder, chatId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(chatId), 0)
}
func CreateChatResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
