// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package WebsocketMessage

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ListMessagesRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsListMessagesRequest(buf []byte, offset flatbuffers.UOffsetT) *ListMessagesRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ListMessagesRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishListMessagesRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsListMessagesRequest(buf []byte, offset flatbuffers.UOffsetT) *ListMessagesRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ListMessagesRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedListMessagesRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ListMessagesRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ListMessagesRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ListMessagesRequest) ChatId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ListMessagesRequest) Page() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ListMessagesRequest) MutatePage(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func ListMessagesRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func ListMessagesRequestAddChatId(builder *flatbuffers.Builder, chatId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(chatId), 0)
}
func ListMessagesRequestAddPage(builder *flatbuffers.Builder, page uint64) {
	builder.PrependUint64Slot(1, page, 0)
}
func ListMessagesRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
