// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package WebsocketMessage

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ListChatsResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsListChatsResponse(buf []byte, offset flatbuffers.UOffsetT) *ListChatsResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ListChatsResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishListChatsResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsListChatsResponse(buf []byte, offset flatbuffers.UOffsetT) *ListChatsResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ListChatsResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedListChatsResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ListChatsResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ListChatsResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ListChatsResponse) Chats(obj *ChatWithLatestMessage, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *ListChatsResponse) ChatsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func ListChatsResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func ListChatsResponseAddChats(builder *flatbuffers.Builder, chats flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(chats), 0)
}
func ListChatsResponseStartChatsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func ListChatsResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
