// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package WebsocketMessage

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ListUsersRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsListUsersRequest(buf []byte, offset flatbuffers.UOffsetT) *ListUsersRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ListUsersRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishListUsersRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsListUsersRequest(buf []byte, offset flatbuffers.UOffsetT) *ListUsersRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ListUsersRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedListUsersRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ListUsersRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ListUsersRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ListUsersRequest) ChatId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func ListUsersRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func ListUsersRequestAddChatId(builder *flatbuffers.Builder, chatId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(chatId), 0)
}
func ListUsersRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
