// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package WebsocketMessage

import "strconv"

type Payload byte

const (
	PayloadNONE                  Payload = 0
	PayloadChatListNotification  Payload = 1
	PayloadUserListNotification  Payload = 2
	PayloadMessageNotification   Payload = 3
	PayloadAddUserResponse       Payload = 4
	PayloadCreateMessageResponse Payload = 5
	PayloadListUsersResponse     Payload = 6
	PayloadCreateChatResponse    Payload = 7
	PayloadListMessagesResponse  Payload = 8
	PayloadListChatsResponse     Payload = 9
	PayloadSendMessageRequest    Payload = 10
	PayloadListChatsRequest      Payload = 11
	PayloadListMessagesRequest   Payload = 12
	PayloadListUsersRequest      Payload = 13
	PayloadCreateChatRequest     Payload = 14
	PayloadAddUserRequest        Payload = 15
)

var EnumNamesPayload = map[Payload]string{
	PayloadNONE:                  "NONE",
	PayloadChatListNotification:  "ChatListNotification",
	PayloadUserListNotification:  "UserListNotification",
	PayloadMessageNotification:   "MessageNotification",
	PayloadAddUserResponse:       "AddUserResponse",
	PayloadCreateMessageResponse: "CreateMessageResponse",
	PayloadListUsersResponse:     "ListUsersResponse",
	PayloadCreateChatResponse:    "CreateChatResponse",
	PayloadListMessagesResponse:  "ListMessagesResponse",
	PayloadListChatsResponse:     "ListChatsResponse",
	PayloadSendMessageRequest:    "SendMessageRequest",
	PayloadListChatsRequest:      "ListChatsRequest",
	PayloadListMessagesRequest:   "ListMessagesRequest",
	PayloadListUsersRequest:      "ListUsersRequest",
	PayloadCreateChatRequest:     "CreateChatRequest",
	PayloadAddUserRequest:        "AddUserRequest",
}

var EnumValuesPayload = map[string]Payload{
	"NONE":                  PayloadNONE,
	"ChatListNotification":  PayloadChatListNotification,
	"UserListNotification":  PayloadUserListNotification,
	"MessageNotification":   PayloadMessageNotification,
	"AddUserResponse":       PayloadAddUserResponse,
	"CreateMessageResponse": PayloadCreateMessageResponse,
	"ListUsersResponse":     PayloadListUsersResponse,
	"CreateChatResponse":    PayloadCreateChatResponse,
	"ListMessagesResponse":  PayloadListMessagesResponse,
	"ListChatsResponse":     PayloadListChatsResponse,
	"SendMessageRequest":    PayloadSendMessageRequest,
	"ListChatsRequest":      PayloadListChatsRequest,
	"ListMessagesRequest":   PayloadListMessagesRequest,
	"ListUsersRequest":      PayloadListUsersRequest,
	"CreateChatRequest":     PayloadCreateChatRequest,
	"AddUserRequest":        PayloadAddUserRequest,
}

func (v Payload) String() string {
	if s, ok := EnumNamesPayload[v]; ok {
		return s
	}
	return "Payload(" + strconv.FormatInt(int64(v), 10) + ")"
}
