{
 "title": "Default Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "/chat (req/s)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(chat_endpoint_request_count[$__rate_interval])",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "req/s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "rate(websocket_write_request_count[30s])",
     "legendFormat": "write"
    },
    {
     "expr": "rate(websocket_read_request_count[30s])",
     "legendFormat": "read"
    }
   ]
  },
  {
   "title": "websocket connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 0 },
   "targets": [
    { "expr": "websocket_connection_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "/user/create (req/s)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "rate(user_create_request_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "opcode req/s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 6, "y": 7 },
   "targets": [
    {
     "expr": "rate(add_user_op_code_request_count[5s])",
     "legendFormat": "add_user"
    },
    {
     "expr": "rate(list_chats_op_code_request_count[$__rate_interval])",
     "legendFormat": "list_chats"
    },
    {
     "expr": "rate(list_users_op_code_request_count[$__rate_interval])",
     "legendFormat": "list_users"
    },
    {
     "expr": "rate(create_chat_op_code_request_count[$__rate_interval])",
     "legendFormat": "create_chat"
    },
    {
     "expr": "rate(send_message_op_code_request_count[$__rate_interval])",
     "legendFormat": "send_message"
    },
    {
     "expr": "rate(list_messages_op_code_request_count[$__rate_interval])",
     "legendFormat": "list_messages"
    }
   ]
  },
  {
   "title": "websocket total MB/s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 13, "y": 7 },
   "targets": [
    {
     "expr": "rate(websocket_message_bytes_read_sum[$__rate_interval]) / 1000000",
     "legendFormat": "read"
    },
    {
     "expr": "rate(websocket_message_bytes_written_sum[$__rate_interval]) / 1000000",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "websocket total MB",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 7 },
   "targets": [
    {
     "expr": "websocket_message_bytes_read_sum / 1000000",
     "legendFormat": "read"
    },
    {
     "expr": "websocket_message_bytes_written_sum / 1000000",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "db: number of rows",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 14 },
   "targets": [
    { "expr": "number_of_chats", "legendFormat": "chats" },
    { "expr": "number_of_messages", "legendFormat": "messages" },
    { "expr": "number_of_users", "legendFormat": "users" }
   ]
  },
  {
   "title": "db: rate/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 14 },
   "targets": [
    {
     "expr": "rate(number_of_chats[$__rate_interval])",
     "legendFormat": "chats"
    },
    {
     "expr": "rate(number_of_messages[$__rate_interval])",
     "legendFormat": "messages"
    },
    {
     "expr": "rate(number_of_users[$__rate_interval])",
     "legendFormat": "users"
    }
   ]
  },
  {
   "title": "websocket_request_duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(websocket_request_duration_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(websocket_request_duration_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(websocket_request_duration_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "sqlite_request_duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(sqlite_request_duration_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(sqlite_request_duration_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(sqlite_request_duration_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "bytes write",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "websocket_message_bytes_written_bucket",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "request count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 13, "y": 30 },
   "targets": [
    { "expr": "websocket_write_request_count", "legendFormat": "write" },
    { "expr": "websocket_read_request_count", "legendFormat": "read" }
   ]
  },
  {
   "title": "opcode request count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 30 },
   "targets": [
    { "expr": "add_user_op_code_request_count", "legendFormat": "{{__name__}}" },
    {
     "expr": "list_chats_op_code_request_count",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "list_users_op_code_request_count",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "create_chat_op_code_request_count",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "send_message_op_code_request_count",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "list_messages_op_code_request_count",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "bytes read",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "websocket_message_bytes_read_bucket",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "websocket_request_duration_bucket",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "websocket_request_duration_bucket",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "sqlite_request_duration_bucket",
   "type": "histogram",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 54 },
   "targets": [
    { "expr": "sqlite_request_duration_bucket", "legendFormat": "__auto" }
   ]
  }
 ]
}