// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

const flatbuffers = window.flatbuffers

export class ChatListNotification {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ChatListNotification {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsChatListNotification(bb:flatbuffers.ByteBuffer, obj?:ChatListNotification):ChatListNotification {
  return (obj || new ChatListNotification()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsChatListNotification(bb:flatbuffers.ByteBuffer, obj?:ChatListNotification):ChatListNotification {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ChatListNotification()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

chatId():string|null
chatId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
chatId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

userId():string|null
userId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
userId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

lastActivity():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

static startChatListNotification(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addChatId(builder:flatbuffers.Builder, chatIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, chatIdOffset, 0);
}

static addUserId(builder:flatbuffers.Builder, userIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, userIdOffset, 0);
}

static addLastActivity(builder:flatbuffers.Builder, lastActivity:bigint) {
  builder.addFieldInt64(2, lastActivity, BigInt('0'));
}

static endChatListNotification(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createChatListNotification(builder:flatbuffers.Builder, chatIdOffset:flatbuffers.Offset, userIdOffset:flatbuffers.Offset, lastActivity:bigint):flatbuffers.Offset {
  ChatListNotification.startChatListNotification(builder);
  ChatListNotification.addChatId(builder, chatIdOffset);
  ChatListNotification.addUserId(builder, userIdOffset);
  ChatListNotification.addLastActivity(builder, lastActivity);
  return ChatListNotification.endChatListNotification(builder);
}
}
