// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

const flatbuffers = window.flatbuffers

export class CreateChatResponse {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):CreateChatResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsCreateChatResponse(bb:flatbuffers.ByteBuffer, obj?:CreateChatResponse):CreateChatResponse {
  return (obj || new CreateChatResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsCreateChatResponse(bb:flatbuffers.ByteBuffer, obj?:CreateChatResponse):CreateChatResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new CreateChatResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

chatId():string|null
chatId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
chatId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startCreateChatResponse(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addChatId(builder:flatbuffers.Builder, chatIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, chatIdOffset, 0);
}

static endCreateChatResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createCreateChatResponse(builder:flatbuffers.Builder, chatIdOffset:flatbuffers.Offset):flatbuffers.Offset {
  CreateChatResponse.startCreateChatResponse(builder);
  CreateChatResponse.addChatId(builder, chatIdOffset);
  return CreateChatResponse.endCreateChatResponse(builder);
}
}
