// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

const flatbuffers = window.flatbuffers

export class ListChatsRequest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ListChatsRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsListChatsRequest(bb:flatbuffers.ByteBuffer, obj?:ListChatsRequest):ListChatsRequest {
  return (obj || new ListChatsRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsListChatsRequest(bb:flatbuffers.ByteBuffer, obj?:ListChatsRequest):ListChatsRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ListChatsRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

uid():string|null
uid(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
uid(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startListChatsRequest(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addUid(builder:flatbuffers.Builder, uidOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, uidOffset, 0);
}

static endListChatsRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createListChatsRequest(builder:flatbuffers.Builder, uidOffset:flatbuffers.Offset):flatbuffers.Offset {
  ListChatsRequest.startListChatsRequest(builder);
  ListChatsRequest.addUid(builder, uidOffset);
  return ListChatsRequest.endListChatsRequest(builder);
}
}
