// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

const flatbuffers = window.flatbuffers

export class ListUsersRequest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ListUsersRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsListUsersRequest(bb:flatbuffers.ByteBuffer, obj?:ListUsersRequest):ListUsersRequest {
  return (obj || new ListUsersRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsListUsersRequest(bb:flatbuffers.ByteBuffer, obj?:ListUsersRequest):ListUsersRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ListUsersRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

chatId():string|null
chatId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
chatId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startListUsersRequest(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addChatId(builder:flatbuffers.Builder, chatIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, chatIdOffset, 0);
}

static endListUsersRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createListUsersRequest(builder:flatbuffers.Builder, chatIdOffset:flatbuffers.Offset):flatbuffers.Offset {
  ListUsersRequest.startListUsersRequest(builder);
  ListUsersRequest.addChatId(builder, chatIdOffset);
  return ListUsersRequest.endListUsersRequest(builder);
}
}
