// automatically generated by the FlatBuffers compiler, do not modify
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
const flatbuffers = window.flatbuffers
export class MessageDB {
    constructor() {
        this.bb = null;
        this.bb_pos = 0;
    }
    __init(i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    }
    static getRootAsMessageDB(bb, obj) {
        return (obj || new MessageDB()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    }
    static getSizePrefixedRootAsMessageDB(bb, obj) {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new MessageDB()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    }
    msgId(optionalEncoding) {
        const offset = this.bb.__offset(this.bb_pos, 4);
        return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
    }
    chatId(optionalEncoding) {
        const offset = this.bb.__offset(this.bb_pos, 6);
        return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
    }
    userId(optionalEncoding) {
        const offset = this.bb.__offset(this.bb_pos, 8);
        return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
    }
    text(optionalEncoding) {
        const offset = this.bb.__offset(this.bb_pos, 10);
        return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
    }
    createdAtMicro() {
        const offset = this.bb.__offset(this.bb_pos, 12);
        return offset ? this.bb.readInt64(this.bb_pos + offset) : BigInt('0');
    }
    static startMessageDB(builder) {
        builder.startObject(5);
    }
    static addMsgId(builder, msgIdOffset) {
        builder.addFieldOffset(0, msgIdOffset, 0);
    }
    static addChatId(builder, chatIdOffset) {
        builder.addFieldOffset(1, chatIdOffset, 0);
    }
    static addUserId(builder, userIdOffset) {
        builder.addFieldOffset(2, userIdOffset, 0);
    }
    static addText(builder, textOffset) {
        builder.addFieldOffset(3, textOffset, 0);
    }
    static addCreatedAtMicro(builder, createdAtMicro) {
        builder.addFieldInt64(4, createdAtMicro, BigInt('0'));
    }
    static endMessageDB(builder) {
        const offset = builder.endObject();
        return offset;
    }
    static createMessageDB(builder, msgIdOffset, chatIdOffset, userIdOffset, textOffset, createdAtMicro) {
        MessageDB.startMessageDB(builder);
        MessageDB.addMsgId(builder, msgIdOffset);
        MessageDB.addChatId(builder, chatIdOffset);
        MessageDB.addUserId(builder, userIdOffset);
        MessageDB.addText(builder, textOffset);
        MessageDB.addCreatedAtMicro(builder, createdAtMicro);
        return MessageDB.endMessageDB(builder);
    }
}
