// automatically generated by the FlatBuffers compiler, do not modify
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
export var Opcode;
(function (Opcode) {
    Opcode[Opcode["LIST_CHATS_RESPONSE"] = 0] = "LIST_CHATS_RESPONSE";
    Opcode[Opcode["LIST_MESSAGES_RESPONSE"] = 1] = "LIST_MESSAGES_RESPONSE";
    Opcode[Opcode["CREATE_CHAT_RESPONSE"] = 2] = "CREATE_CHAT_RESPONSE";
    Opcode[Opcode["LIST_USERS_RESPONSE"] = 3] = "LIST_USERS_RESPONSE";
    Opcode[Opcode["CREATE_MESSAGE_RESPONSE"] = 4] = "CREATE_MESSAGE_RESPONSE";
    Opcode[Opcode["ADD_USER_RESPONSE"] = 5] = "ADD_USER_RESPONSE";
    Opcode[Opcode["MESSAGE_NOTIFICATION"] = 6] = "MESSAGE_NOTIFICATION";
    Opcode[Opcode["USER_LIST_NOTIFICATION"] = 7] = "USER_LIST_NOTIFICATION";
    Opcode[Opcode["CHAT_LIST_NOTIFICATION"] = 8] = "CHAT_LIST_NOTIFICATION";
    Opcode[Opcode["SEND_MESSAGE_REQUEST"] = 9] = "SEND_MESSAGE_REQUEST";
    Opcode[Opcode["LIST_CHATS_REQUEST"] = 10] = "LIST_CHATS_REQUEST";
    Opcode[Opcode["LIST_MESSAGES_REQUEST"] = 11] = "LIST_MESSAGES_REQUEST";
    Opcode[Opcode["LIST_USERS_REQUEST"] = 12] = "LIST_USERS_REQUEST";
    Opcode[Opcode["CREATE_CHAT_REQUEST"] = 13] = "CREATE_CHAT_REQUEST";
    Opcode[Opcode["ADD_USER_REQUEST"] = 14] = "ADD_USER_REQUEST";
})(Opcode || (Opcode = {}));
