// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum Opcode {
  LIST_CHATS_RESPONSE = 0,
  LIST_MESSAGES_RESPONSE = 1,
  CREATE_CHAT_RESPONSE = 2,
  LIST_USERS_RESPONSE = 3,
  CREATE_MESSAGE_RESPONSE = 4,
  ADD_USER_RESPONSE = 5,
  MESSAGE_NOTIFICATION = 6,
  USER_LIST_NOTIFICATION = 7,
  CHAT_LIST_NOTIFICATION = 8,
  SEND_MESSAGE_REQUEST = 9,
  LIST_CHATS_REQUEST = 10,
  LIST_MESSAGES_REQUEST = 11,
  LIST_USERS_REQUEST = 12,
  CREATE_CHAT_REQUEST = 13,
  ADD_USER_REQUEST = 14
}
