// automatically generated by the FlatBuffers compiler, do not modify
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
import { AddUserRequest } from '../websocket-message/add-user-request.js';
import { AddUserResponse } from '../websocket-message/add-user-response.js';
import { ChatListNotification } from '../websocket-message/chat-list-notification.js';
import { CreateChatRequest } from '../websocket-message/create-chat-request.js';
import { CreateChatResponse } from '../websocket-message/create-chat-response.js';
import { CreateMessageResponse } from '../websocket-message/create-message-response.js';
import { ListChatsRequest } from '../websocket-message/list-chats-request.js';
import { ListChatsResponse } from '../websocket-message/list-chats-response.js';
import { ListMessagesRequest } from '../websocket-message/list-messages-request.js';
import { ListMessagesResponse } from '../websocket-message/list-messages-response.js';
import { ListUsersRequest } from '../websocket-message/list-users-request.js';
import { ListUsersResponse } from '../websocket-message/list-users-response.js';
import { MessageNotification } from '../websocket-message/message-notification.js';
import { SendMessageRequest } from '../websocket-message/send-message-request.js';
import { UserListNotification } from '../websocket-message/user-list-notification.js';
export var Payload;
(function (Payload) {
    Payload[Payload["NONE"] = 0] = "NONE";
    Payload[Payload["ChatListNotification"] = 1] = "ChatListNotification";
    Payload[Payload["UserListNotification"] = 2] = "UserListNotification";
    Payload[Payload["MessageNotification"] = 3] = "MessageNotification";
    Payload[Payload["AddUserResponse"] = 4] = "AddUserResponse";
    Payload[Payload["CreateMessageResponse"] = 5] = "CreateMessageResponse";
    Payload[Payload["ListUsersResponse"] = 6] = "ListUsersResponse";
    Payload[Payload["CreateChatResponse"] = 7] = "CreateChatResponse";
    Payload[Payload["ListMessagesResponse"] = 8] = "ListMessagesResponse";
    Payload[Payload["ListChatsResponse"] = 9] = "ListChatsResponse";
    Payload[Payload["SendMessageRequest"] = 10] = "SendMessageRequest";
    Payload[Payload["ListChatsRequest"] = 11] = "ListChatsRequest";
    Payload[Payload["ListMessagesRequest"] = 12] = "ListMessagesRequest";
    Payload[Payload["ListUsersRequest"] = 13] = "ListUsersRequest";
    Payload[Payload["CreateChatRequest"] = 14] = "CreateChatRequest";
    Payload[Payload["AddUserRequest"] = 15] = "AddUserRequest";
})(Payload || (Payload = {}));
export function unionToPayload(type, accessor) {
    switch (Payload[type]) {
        case 'NONE': return null;
        case 'ChatListNotification': return accessor(new ChatListNotification());
        case 'UserListNotification': return accessor(new UserListNotification());
        case 'MessageNotification': return accessor(new MessageNotification());
        case 'AddUserResponse': return accessor(new AddUserResponse());
        case 'CreateMessageResponse': return accessor(new CreateMessageResponse());
        case 'ListUsersResponse': return accessor(new ListUsersResponse());
        case 'CreateChatResponse': return accessor(new CreateChatResponse());
        case 'ListMessagesResponse': return accessor(new ListMessagesResponse());
        case 'ListChatsResponse': return accessor(new ListChatsResponse());
        case 'SendMessageRequest': return accessor(new SendMessageRequest());
        case 'ListChatsRequest': return accessor(new ListChatsRequest());
        case 'ListMessagesRequest': return accessor(new ListMessagesRequest());
        case 'ListUsersRequest': return accessor(new ListUsersRequest());
        case 'CreateChatRequest': return accessor(new CreateChatRequest());
        case 'AddUserRequest': return accessor(new AddUserRequest());
        default: return null;
    }
}
export function unionListToPayload(type, accessor, index) {
    switch (Payload[type]) {
        case 'NONE': return null;
        case 'ChatListNotification': return accessor(index, new ChatListNotification());
        case 'UserListNotification': return accessor(index, new UserListNotification());
        case 'MessageNotification': return accessor(index, new MessageNotification());
        case 'AddUserResponse': return accessor(index, new AddUserResponse());
        case 'CreateMessageResponse': return accessor(index, new CreateMessageResponse());
        case 'ListUsersResponse': return accessor(index, new ListUsersResponse());
        case 'CreateChatResponse': return accessor(index, new CreateChatResponse());
        case 'ListMessagesResponse': return accessor(index, new ListMessagesResponse());
        case 'ListChatsResponse': return accessor(index, new ListChatsResponse());
        case 'SendMessageRequest': return accessor(index, new SendMessageRequest());
        case 'ListChatsRequest': return accessor(index, new ListChatsRequest());
        case 'ListMessagesRequest': return accessor(index, new ListMessagesRequest());
        case 'ListUsersRequest': return accessor(index, new ListUsersRequest());
        case 'CreateChatRequest': return accessor(index, new CreateChatRequest());
        case 'AddUserRequest': return accessor(index, new AddUserRequest());
        default: return null;
    }
}
