// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

const flatbuffers = window.flatbuffers

export class SendMessageRequest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SendMessageRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSendMessageRequest(bb:flatbuffers.ByteBuffer, obj?:SendMessageRequest):SendMessageRequest {
  return (obj || new SendMessageRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSendMessageRequest(bb:flatbuffers.ByteBuffer, obj?:SendMessageRequest):SendMessageRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SendMessageRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

chatId():string|null
chatId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
chatId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

uid():string|null
uid(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
uid(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

text():string|null
text(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
text(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startSendMessageRequest(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addChatId(builder:flatbuffers.Builder, chatIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, chatIdOffset, 0);
}

static addUid(builder:flatbuffers.Builder, uidOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, uidOffset, 0);
}

static addText(builder:flatbuffers.Builder, textOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, textOffset, 0);
}

static endSendMessageRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createSendMessageRequest(builder:flatbuffers.Builder, chatIdOffset:flatbuffers.Offset, uidOffset:flatbuffers.Offset, textOffset:flatbuffers.Offset):flatbuffers.Offset {
  SendMessageRequest.startSendMessageRequest(builder);
  SendMessageRequest.addChatId(builder, chatIdOffset);
  SendMessageRequest.addUid(builder, uidOffset);
  SendMessageRequest.addText(builder, textOffset);
  return SendMessageRequest.endSendMessageRequest(builder);
}
}
